#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Daftarkan Composer Autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
(require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);
